### ISSUE TITLE
mailto links support

### ISSUE THREAD

**Issue by sikmir** [shtanton/gmi2html#14]
For now only `https` links properly translated to `<a href="...">...</a>`.
https://github.com/shtanton/gmi2html/blob/2ee16d29c2ffd4057f2e89efb0d323ef79c70010/src/main.zig#L20
But it would be nice to handle `mailto` links in the same way.

**Comment by shtanton** [comment]
Yep, I'll add that when I get time or accept a pull request if someone beats me to it

**Comment by sikmir** [comment]
Thanks!
