### ISSUE TITLE
Release pre-built binaries

### ISSUE THREAD

**Issue by eggplants** [shtanton/gmi2html#17]
Like [v0.4.0 Release](https://github.com/shtanton/gmi2html/releases/tag/v0.4.0), please upload and distribute pre-built binaries in [v0.4.1](https://github.com/shtanton/gmi2html/releases/tag/v0.4.1).

**Comment by shtanton** [comment]
Done, I haven't been very active with zig lately and I have no clue why the binary size ballooned up to 610kb but oh well

**Comment by eggplants** [comment]
Try: `zig build-exe src/main.zig -O ReleaseSmall --strip`

It made a 17kb binary.
